language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && source ~/.nvm/nvm.sh && nvm install 4.2
script:
  - bash scripts/site-setup.sh

